config/routes.rb
OshDesigns::Application.routes.draw do

  get "set_language/english"

  get "set_language/hebrew"

root :to => 'pages#home'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"  , :registrations => 'registrations'} 
  resources :users, :only => [:show]
  resources :orders , :only => [:create , :edit , :destroy,:new]
   match '/about',    to: 'pages#about'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name , :min_price , :max_price , :min_days_work , :max_days_work
  has_many :templates, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base

	attr_accessible :description, :order_type , :title,:cancel 
	belongs_to :category
	belongs_to :user
	mount_uploader :image, ImageUploader
	
	validates :user_id, presence: true
	attr_accessor :accessible
	# default_scope order: 'orders.created_at'
	scope :in_progress  , where("orders.state ='in progress' ")
	scope :unwatched  , where("orders.state ='unwatched' ")
	scope :completed  , where("orders.state ='completed' ")
	scope :paid  , where("orders.state ='paid' ")
	scope :unpaid , where("orders.state !='paid' ")
	scope :request_to_cancel , where(cancel: true)

	def self.total_on(date)
		where("date(created_at) = ?",date).sum(:price)
	end

	private

	def mass_assignment_authorizer(role = :default)
		if accessible == :all
			self.class.protected_attributes
		else
			super + (accessible || [])
		end
	end
end

app/models/template.rb
class Template < ActiveRecord::Base
  attr_accessible :category_id, :title,:template
  belongs_to :category
  mount_uploader :template, TemplateUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable , :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :phone,:email,:name, :password, :password_confirmation, :remember_me , :provider , :uid
  
  #orders
has_many :orders, dependent: :destroy
  VALID_PHONE_REGEX =/((^05[0-9]-[0-9]{7}$)|(^0[1-9]-[0-9]{7}$)|(^05[0-9]{8}$)|(^0[1-9][0-9]{7}$))/
  validates :name, :presence => true

  validate :check_phone

  def check_phone
    if !(phone.blank? || phone.nil?) and !(self.phone =~ VALID_PHONE_REGEX)
      errors.add(:phone, "should look like valid phone number")
    end
  end


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user 
      user = check_if_already_exists_and_update(auth)
      unless user
       user = User.create(name:auth.extra.raw_info.name,
         provider:auth.provider,
         uid:auth.uid,
         email:auth.info.email,
         password:""
         )
     end

   end
   user
 end



 def self.check_if_already_exists_and_update(auth)
   user = User.find_by_email(auth.info.email)
   if user
    user.update_attributes(provider:auth.provider , uid: auth.uid)
  end
  user
end

def password_required?
  provider.blank? && super
end

def update_with_password(params,*options)
  if encrypted_password.blank?
    update_attributes(params,*options)
  else
    super
  end
end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	# def after_sign_in_path_for(resource)
	# 	about_path
	# end

  before_filter :set_locale
 
  private
  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
   before_filter :authenticate_user! 
   before_filter :should_have_phone , only: [:new,:create]
   before_filter :correct_user,   only: :destroy

   def create
    @order = current_user.orders.build(params[:order])
    if @order.save
      flash[:success] = "Order created!"
      UserMailer.annonce_admin_on_order(@order).deliver
      redirect_to current_user
    else
      render 'orders/new'
    end

  end

  def edit
  end

  def destroy
    notice =  "order cancelation sent to designer"
    if @order.cancel
       @order.update_attributes(:cancel=>false)
       notice = "order cacneletion has been canceld"
    else
   @order.update_attributes(:cancel=>true)
 end
   redirect_to current_user, :notice =>notice
  end

  def new
   @order = current_user.orders.build
  end



  private

    def correct_user
      @order = current_user.orders.find_by_id(params[:id])
      redirect_to root_url if @order.nil?
    end

    def should_have_phone
      if (current_user.phone.nil? || current_user.phone.blank?) 
        flash[:notice] = "You Need To Enter Valid Phone In Order To Create Orders"
        redirect_to edit_user_registration_path(current_user)
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def destroy
	end
	def create
		super
		if !current_user.nil?
			UserMailer.register_welcome(current_user).deliver
		end
		
	end
end

app/controllers/set_language_controller.rb
class SetLanguageController < ApplicationController
  def english
    I18n.locale = :en
    set_session_and_redirect
  end

  def hebrew
    I18n.locale = :he
    set_session_and_redirect
  end


  private
  def set_session_and_redirect
    session[:locale] = I18n.locale
    redirect_to :back
    rescue ActionController::RedirectBackError
      redirect_to :root
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user! 
	def show
		begin
			@user = User.find(params[:id])
			@orders = @user.orders
		rescue ActiveRecord::RecordNotFound  
			redirect_to root_path , :alert => "No Such User"
			return
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
  	resource.class
  end

  def flash_key_to_alert(key)
    if key=="notice"
    result = "info" 
    elsif key=="alert"
      result = "error"
    else
      result = key
    end
      result
  end

  def order_types
    ["Logo","Banner", "Web Site"]
  end
end

app/helpers/orders_helper.rb
module OrdersHelper

	# def orders_chart_series(orders, start_time)
	# 	orders_by_day = orders.where(:created_at => start_time.beginning_of_day..Time.zone.now.end_of_day).
	# 	group("date(created_at)").
	# 	select("date(created_at), sum(price) as price")
	# 	(start_time.to_date..Date.today).map do |date|
	# 		order = orders_by_day.detect { |order| order.created_at.to_date == date }
	# 		order && order.price.to_f || 0
	# 	end.inspect
	# end

	
  def order_types
    ["Logo","Banner", "Web Site"]
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/set_language_helper.rb
module SetLanguageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_order_actions.html.erb
<%= link_to "Edit", edit_admin_order_path(order) %> <br>
<% if order.image? %>
	<%= link_to "Edit  Work", complete_admin_order_path(order)  %>
<% else %>
	<%= link_to "Submit Work", complete_admin_order_path(order)  %>
<% end %>
<%= link_to(I18n.t('active_admin.delete'), resource_path(order), :method => :delete, :data => {:confirm => I18n.t('active_admin.delete_confirmation')}, :class => "member_link delete_link") %>


<!-- <div id="login-box<%= order.id %>" class="login-popup">
    <a href="#" class="close"><img src="/assets/close_pop.png" class="btn_close" title="Close Window" alt="Close" /></a>>
    <%= form_for order ,:url => "/admin/orders/#{order.id}" ,:class=> "signin" do |f| %>
    <%= f.select :state, ["unwatched" , "in progress" ,"completed" , "paid"] %>
    <%= f.submit "Change" %>
    <% end %>  
</div> -->

app/views/admins/_order_chart.html.erb

<script type="text/javascript">
  $(function () {
    new Highcharts.Chart({
         chart: { renderTo: 'orders_chart' },
    title: { text: 'Orders by Day Created' },
    xAxis: { type: 'datetime' },
    yAxis: {
      title: { text: 'Shkalim'}
    },
    tooltip: {
      formatter: function () {
        return Highcharts.dateFormat("%B %e %Y", this.x) + ': ' +
          '₪' + Highcharts.numberFormat(this.y, 2);
      }
    },
    series: [
    <% {"Unpaid" => Order.unpaid , "Paid" => Order.paid }.each do |name,orders| %>{
    	name: "<%= name %>",
    	pointInterval: <%= 1.day * 1000 %>,
      pointStart: <%= 1.month.ago.at_midnight.to_i * 1000 %>,
      data:  <%= (1.month.ago.to_date..Date.today).map { |date| orders.total_on(date).to_f}.inspect %>
    
    },
    <% end %>

    ]
    });
  });
</script>
<div id="orders_chart" style="width: 560px; height: 300px;"></div>

app/views/admins/_order_state_change.html.erb
<%= form_for order ,:url => "/admin/orders/#{order.id}" ,:class=> "change_state_form" do |f| %>
    <%= f.select :state, ["unwatched" , "in progress" ,"completed" , "paid"] ,:selected => order.state %>
    <%= f.submit "Change" %>
    <% end %>

app/views/admins/order_submit.html.erb
<h2><%= "Submiting Order #{@order.title}" %></h2>
 <% if @order.image? %>
 	<h3> Already Submitted: </h3>
	<%= link_to image_tag(@order.image_url(:thumb)), @order.image_url ,:target =>"_blank"  %>
	<br>
	<br>
	<h3>If u want to change:</h3>
<% end %>


<%= form_for @order, :url => "/admin/orders/#{@order.id}", :html => {:multipart => true} do |f| %>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer" >


        <div class="lang">
          <%=  image_tag("he.png", :border => 0) %>
          <%= link_to_unless I18n.locale == :he, "עברית", set_language_hebrew_path %>
          |
          <%= image_tag("en.png", :border => 0) %>
            <%= link_to_unless I18n.locale == :en, "English", set_language_english_path %>
        </div>
    
</footer>

app/views/layouts/_header.html.erb
<div class = "navbar">
	<div class="pull-right">
		<% if user_signed_in? %>
		<div id="fat-menu" class="dropdown">
			<a href="#" class=" btn dropdown-toggle" data-toggle="dropdown">
				<%= t('header.toggle_main') %> <b class="caret"></b>
			</a>
			<ul class="dropdown-menu">
				<li><%= link_to t('header.toggle_profile_link'),current_user %></li>
				<li><%= link_to t('header.toggle_profile_settings'), edit_user_registration_path(current_user) %></li>
				<li class="divider"></li>
				<li>
					<%= link_to t('header.toggle_log_out'), destroy_user_session_path, method: "delete" %>
				</li>
			</ul>
		</div>
		<% else %>
		<%= link_to  raw("<i class=\"icon-user icon-white\"></i>#{ t('header.sign_in_button_text')} ") , new_user_session_path ,
		:class => "btn btn-primary" %> <%= t('words.or') %>
		<%= link_to t('header.facebook_sign_in_button_text'), user_omniauth_authorize_path(:facebook) , :class => "zocial facebook" %>
		<% end %>
		
	</div>
	<div class="headTitle">
		<%= link_to raw('<h2> ArtiPixel</h2>'), root_path %>
	</div>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtiPixel</title>
  <%= stylesheet_link_tag    "application-all", media: "all" %>
  <%= javascript_include_tag "application" %>
  <% if  I18n.locale == :he%>
  <%= stylesheet_link_tag    "application-rtl", media: "all" %>
  <% end %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">if (window.location.href.indexOf('#_=_') > 0) {
    window.location = window.location.href.replace(/#.*/, '');
  };</script>

  <script type="text/javascript">
<!--
    function toggle_visibility(id) {
       var e = document.getElementById(id);
       var b = document.getElementById("buttonimg");
       if(e.style.display == 'block'){
          e.style.display = 'none';
        }
       else{
          e.style.display = 'block';
        }
    }

    function change_arrow(id) {
       var e = document.getElementById(id);
       if(e.src.indexOf("right") !== -1 ){
          e.src = "/assets/down.png";
        }
       else{
                    e.src = "/assets/right.png";
        }
    }

//-->
</script>





</head>

<body>
  <div class = "container-narrow">
    <%= render 'layouts/header' %>
    <% flash.each do |key,value|  %>
    <div class="alert alert-<%= flash_key_to_alert(key.to_s) %>">
      <%= value %>
    </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  
</body>
</html>

app/views/orders/_order.html.erb
 <li>
 	<div class="order">
 		<p><b><%= order.title %></b>
 			<a href="#" onclick="toggle_visibility('more-info<%= order.id %>');change_arrow('buttonimg<%= order.id %>');">
 				<%= image_tag("right.png", alt: "more-info",size:"18x18",:id=>"buttonimg#{order.id}") %>
 			</a>
 			<% if current_user  == order.user %>
 				<% if !order.cancel  %>
		 			<%= link_to "DE", order, method: :delete,
		 			data: { confirm: 'You sure?' },
		 			title: order.title , class:"trash" %>
	 			<% else %>
	 				<%= link_to "DE", order, method: :delete,
		 			data: { confirm: 'This Will Cancel The Cancelation' },
		 			title: order.title , class:"trashX" %>
	 			<% end %>

 			<% end %>
 		</p>

 		<div id="more-info<%= order.id %>" style="display:none">
 			<b>State</b> : <%= order.state %>
 			<br>
 			<b> Estimated Finshed </b>: <%= order.expected_end.nil? ? "Unknown" : order.expected_end%>
 			<br>
 			<b>Type</b>: <%= order.order_type %>
 			<br>
 			<b>Price</b>: <%= order.price %>
 			<br>
 			<b>Order ID </b>: <%= order.id %>
 			<br>
 			<b>Description</b>: 
 			<br>
 			<%= raw(order.description) %>
 			<br>
 			<% if order.image? %>
 			<b>Submitted Work By Designer</b>: 
 			<br>
 			<%= link_to image_tag(order.image_url(:thumb)), order.image_url ,:target =>"_blank"  %>
 			<% end %>
 		</div>

 		
 		<div class="progress progress-striped">
 			<div class="bar bar-success" style="width: <%= order.state != "unwatched" ? order.percentage  : 0%>%;"></div>
 			<div class="bar bar-warning" style="width: <%= order.state != "unwatched" ? 100-order.percentage  : 0%>%;"></div>
 			<div class="bar bar-danger" style="width: <%= order.state == "unwatched" ? 100  : 0%>%;"></div>
 		</div>
 	</div>
 </li>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/new.html.erb
<div class="row">
<div class="span5 order-form">
	<h1><%= t('order.form_header') %></h1>
	<br>
	<%= form_for(@order) do |f| %>
	<%= f.text_field :title, placeholder: t('order.form_title_placeholder')%>
	<br>
	<p><b> <%= t('order.form_ordertype') %></b></p>
	<%= f.select :order_type, order_types %>
	<br>
	<p><b><%= t('order.form_description') %></b></p>
<%= f.rte_field :description, :toolbar => 'basic', :rows => 8, :cols => 80 , :style => "width:365px;" %>
	<br>
	<br>

	<%= f.submit t('order.form_button_text'), class: "btn btn-large btn-warning  btn-block" %>
	<% end %>


</div>

<div class="span 3 offset1 order-types">
	
	<div class="row order_types round">
		<h2> <%= t('order.order_types.title') %></h2>
		<div class="info_order">
			<div class="title"><b><%= t('order.order_types.banner_name') %></b></div>
			<div class="info_order_info">
				<%= t('words.price_range') %> : 100-250
			</div>
			<div class="info_order_info">
				<%= t('words.work_days') %> : 1-2
			</div>

		</div>
		<br>
		<div class="info_order">
			<div class="title"><b><%= t('order.order_types.logo_name') %></b></div>
			<div class="info_order_info">
				<%= t('words.price_range') %> : 300-500
			</div>
			<div class="info_order_info">
				<%= t('words.work_days') %> : 2-4 
				
			</div>
		</div>
		<br>
		<div class="info_order">
			<div class="title"><b><%= t('order.order_types.web_site_name') %></b></div>
			<div class="info_order_info">
				<%= t('words.price_range') %> : 1000-1500
			</div>
			<div class="info_order_info">
				<%= t('words.work_days') %> : 7-14
			</div>
		</div>
		


	</div>
</div>

</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="row">
	<div class="span6 home-welcome">
		<h1> ArtiPixel</h1>
		<p><%= t('home.welcome_1st') %></p>
		<p><%= t('home.welcome_2nd') %></p>
	</div>
	<div class="span3 home-buttons">
		<% if user_signed_in? %>
		<br>
	<%= link_to  raw("<i class=\"icon-envelope icon-white\"></i> #{t('home.button_order')}") ,new_order_path ,
		:class => "btn btn-large btn-warning  btn-block" %>
		<br>
		<%= link_to raw("<i class=\"icon-user icon-white\"></i>  #{t('home.button_profile')}") ,current_user,
		:class => "btn btn-large btn-block btn-custom" %>

		<% else %>
		<%= render 'devise/registrations/new' %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h3>My Contact Info</h3>
<div class="row">
	<div class="span2">
		<label >Email</label>
	</div>
	<div class="span1">
		<p><%= @user.email %></p>
	</div>
</div>
<div class="row">
	<div class="span2">
		<label >Phone</label>
	</div>
	<div class="span1">
		<p><%= @user.phone %></p>
	</div>
</div>
<br>
<div class="row">
	<% if @orders.any? %>
	<div class ="span5">
		<h3>My Orders</h3>
		<ol class="orders">
			<%= render @orders %>
		</ol>
	</div>
	<% end %>
</div>